### PR TITLE
Feature: Localizable tegaki.js 

### PR DESCRIPTION
**Pull request by mcddx330**
This change is separate any label construction to each language files on tegaki.js. And I created Japanese version.
(select manuality or error becomes fallback to English)

notice: currently, need to re-choose language select on settings. please edit if can fix it.
(this is might be state handler on vue. sorry I'm not familier it.)

English:
image

Japanese:
image

### CODE REVIEW

**Comment by purifetchi** [comment]
omg, this is amazing work, thank you!!!

the actual language is kept in "usePersistentStore()", maybe you can fetch it from there?

**Comment by purifetchi** [comment]
also now that i wonder, maybe we should move the tegaki string to the locale files, and use `i18next.t("tag")` to fetch the data?
it would make everything nicely sit in one place

**Comment by mcddx330** [comment]
@purifetchi 

> also now that i wonder, maybe we should move the tegaki string to the lang.ts locale files under a category like tegaki, and use i18next.t("tegaki.string_name") to fetch the data?
it would make everything nicely sit in one place

so each localize are same one language file and use key-values like
```JSON
{
  "tegakijs": {
    "open": "open",
    "export": "export"
    // ...
  }
}
```
?

> the actual language is kept in "usePersistedStore()", maybe you can fetch it from there? it would then work when the app is started with a non-english language

ok. I'll try it.

**Comment by purifetchi** [comment]
> so each localize are same one language file and use key-values like
> 
> ```json
> {
>   "tegakijs": {
>     "open": "open",
>     "export": "export"
>     // ...
>   }
> }
> ```
> 
> ?

yup! ^^

**Comment by mcddx330** [comment]
fixed it. please check it. @purifetchi

**Comment by purifetchi** [comment]
fantastic work, thank you so so much!!! ^^

**Pull request merged**
